app:
  name: "Microkube"
  domain: "app.local"
  subdomain: "www"
ssl:
  enabled: true
  email: "support@example.com"
images:
  peatio: kenexllc/peatio:2.1.16
  barong: kenexllc/barong:2.1.4
  frontend: kenexllc/mikroapp:0.1.5
  tower: kenexllc/tower:0.1.16
  postmaster: quay.io/openware/postmaster:0.0.3
  arke: kenexllc/arke:0.1.9
vendor:
  frontend: https://github.com/rubykube/mikroapp.git
storage:
  provider: "Google"
  bucketName: "microkube-barong-docs-bucket"
  accessKey: "**********"
  secretKey: "**********"
terraform:
  credentials: "~/safe/microkube.json"
  project: "example-microkube"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "microkube-cloud"
  machine_type: "n1-standard-4"
  image: "debian-cloud/debian-9"
twilio:
  phone_number: "+15005550000"
  account_sid: "changeme"
  auth_token: "changeme"
sendgrid_api_key: changeme
arke:
  strategy:
    type: 'copy'
    pair: 'ETHUSD'
    target:
      driver: rubykube
      host: 'http://www.app.local'
      name: John
      key: changeme
      secret: changeme
    sources:
      - driver: bitfinex
        name: Joe
        key: changeme
        secret: changeme
